### ISSUE TITLE
BottleSpecification.revision is deprecated

### ISSUE THREAD

**Issue by scolby33** [NiLuJe/homebrew-kindletool#1]
I was running `brew update` this morning and received the following warning message:

```
Warning: Calling BottleSpecification.revision is deprecated!
Use BottleSpecification.rebuild instead.
/usr/local/Homebrew/Library/Taps/niluje/homebrew-kindletool/Formula/libarchive.rb:23:in `block in <class:Libarchive>'
Please report this to the niluje/kindletool tap!
```

I'm not really familiar with the internals of Homebrew, but I guess something changed in a recent update and [this line](https://github.com/NiLuJe/homebrew-kindletool/blob/fa909029860cbedb9c6aff276e9ed735bd817095/Formula/libarchive.rb#L23) needs to be changed.

**Comment by NiLuJe** [comment]
Yeah, I just saw that, too. I'll look into it in a few days, thanks for the heads up ;).

**Comment by NiLuJe** [comment]
Okay, pushed something that seems to have put things back in order... :).
